name: Release

on:
  push:
    branches:
      - release
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag to release (e.g., v1.2.3)'
        required: true

env:
  PROJECT_NAME: swellow

jobs:
  get-version:
    name: Get Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.extract_version.outputs.version }}
    steps:
      - name: Extract version from tag or input
        id: extract_version
        run: |
          if [[ "${{ github.event_name }}" == "push" ]]; then
            VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          else
            VERSION=${{ github.event.inputs.tag_name }}
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT

  publish-rust-binaries:
    name: Publish Rust Binaries to GitHub Release
    needs: [get-version]
    runs-on: ubuntu-latest
    outputs:
      version: ${{ needs.get-version.outputs.version }}
    steps:
      - name: Promote draft release to full release
        run: gh release edit ${{ needs.get-version.outputs.version }} --draft=false

  publish-pypi:
    name: Publish to PyPI
    needs: [get-version]
    environment:
      name: pypi
      url: https://pypi.org/p/${{ env.PROJECT_NAME }}
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Download release assets
        uses: actions/download-artifact@v4
        with:
          name: release-assets
          path: release-assets

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1
        with:
          packages-dir: release-assets/